version: "2.4"
services:
  webhost:
    image: nginx
    container_name: webhost
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
    volumes:
      - ./html:/usr/share/nginx/html
    healthcheck:
      test: "curl http://localhost/"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - back
      - db
  db:
    image: mongo:4
    container_name: storage
    restart: always
    volumes:
      - ./data:/data/db
    command: mongod --auth
    ports:
      - 27017:27017
    networks:
      - db

networks:
  back:
    driver: bridge
  db:
    driver: bridge