version: "2.4"
services:
  webhost:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always    
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
 